### PR TITLE
Support Thumbor resizing service

### PR DESCRIPTION
**Pull request by timkelty**

### CODE REVIEW

**Comment by timkelty** [comment]
@khalwat Don't merge yet, hence the WIP :)

Few questions:

#### What do you think we should do when a service doesn't support something?

e.g. AFAIK, Thumbor can't do the "stretch" transform mode (which probably isn't used much anyhow).
Should I throw an exception, or just provide some equivalent and log a warning?

Similarly, the `interlace` setting is something you have to configure server-level for Thumbor, you can't do it as an option. I'm leaning toward just carrying on (don't throw exception) and logging a warning?

#### getWebPUrl should have the same or similar signature as getTransformUrl
We talked about this on slack and you seemed to agree.

**Comment by khalwat** [comment]
> What do you think we should do when a service doesn't support something?

I think you should fall back on some other reasonable setting, and log a soft error. IO proceeds with the assumption that if you're replacing the transform method, that it can do at least what Craft can do internally via transforms.

> getWebPUrl should have the same or similar signature as getTransformUrl

Yep, I will be doing this for you. It makes sense -- it won't be the same signature though, it'll likely have an additional parameter that is the already generated regular URL. Because for many transform methods, it's much easier to just manipulate the URL rather than generate a whole new transform.

**Comment by khalwat** [comment]
https://github.com/nystudio107/craft-imageoptimize/commit/b883946131ec36203700f68bf3599ff77c624fc5

**Comment by timkelty** [comment]
Ok @khalwat – ready for merge

**Pull request merged**
