### PR TITLE
Add optimize/queue-assets for batching individual assets

### PR DESCRIPTION
**Pull request by hahnzilla**
We ran into an issue when we were switching to this plugin where we have
16K images that needed processing. The one task to process all images
took about a week because we had to restart it multiple times and
manually change the offset to make sure it would start at new images.

It didn't occur until we were about to launch that there already
existed a queue job that would process a single image. So we wrote a
quick script to batch those.

I wasn't sure if this was the type of thing that a plugin would want to
support, but wanted to offer it in the event you've had other devs run
into a similar problem.

-----

Can run the console command:

`./craft image-optimize/optimize/queue-assets`

### CODE REVIEW

**Comment by khalwat** [comment]
I appreciate it -- I'm going to have to look at this to see what the best way to handle it might be.

I'm curious how batching in this manner can solve the memory issues, I guess the initial query is just too large?

**Comment by khalwat** [comment]
So interestingly, I'm already grabbing this data in batches using `.each()` ->

https://github.com/nystudio107/craft-imageoptimize/blob/v1/src/jobs/ResaveOptimizedImages.php#L72

Which will grab them in the default batches of `100` results, and iterate through them one by one:

https://www.yiiframework.com/doc/api/2.0/yii-db-query#each()-detail

so.... I'm unclear why the PR works for you, but what I have in place already does not?

**Comment by hahnzilla** [comment]
We had 16K assets that we needed to run this on which takes quite a bit of time :) 

The `each` is probably a way more succinct way of doing that portion. The main part here is that this is creating 16K queue jobs rather than 1 queue job. (1 queue job for each asset)

In our experience, we were unable to get the 1 queue job (for the site) to ever run all the way because it would fail midway through and then start over from the beginning next time we tried. With creating a queue job for each individual asset we could fix or retry the individual assets that failed.

**Comment by hahnzilla** [comment]
Also just checked out `->each()` and that made my day so much brighter. Thank you for sharing that.

**Comment by khalwat** [comment]
Looks like some people are running into this outside of ImageOptimize as well: https://github.com/craftcms/aws-s3/issues/22

**Comment by thinkflo** [comment]
I'm running into the same problem.  Looks like the token is expiring midway and causing the job to fail.  This is from my queue.log

`2019-07-09 17:50:59 [-][1][-][profile end][yii\db\Command::execute] UPDATE queue SET fail=1, dateFailed='2019-07-09 15:50:59', error='Error executing "ListObjects" on "https://s3.[region].amazonaws.com/[bucket name here]?prefix=assets%2F[filename].jpg%2F&max-keys=1&encoding-type=url"; AWS HTTP error: Client error: GET https://s3.[region].amazonaws.com/[bucket name here]?prefix=assets%2F[filename].jpg%2F&max-keys=1&encoding-type=url resulted in a 400 Bad Request response:\n<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>ExpiredToken</Code><Message>The provided token has expired.</Message (truncated...)\n ExpiredToken (client): The provided token has expired. - <?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>ExpiredToken</Code><Message>The provided token has expired.</Message><Token-0>[Token here]</Token-0><RequestId>44F015713C9E39FB</RequestId><HostId>[host id here]</HostId></Error>' WHERE id='1904'`

**Comment by khalwat** [comment]
I created a PR to address this issue in the `aws-s3` package from P&T: https://github.com/craftcms/aws-s3/pull/61/commits/71623bafb7e05dec53ea98cc1a013a5ec14e0011

**Comment by khalwat** [comment]
This should be fixed in the [aws-s3](https://github.com/craftcms/aws-s3) plugin now in version 1.2.4 -> https://github.com/craftcms/aws-s3/blob/master/CHANGELOG.md#124---2019-07-17

@dhahn @thinkflo

**Pull request closed without merging**
